"""AI framework router. The framework name is part of the URL
(/api/vehicle-explore/{framework}/search) so requests can route to different agent
implementations. 'langgraph' is the implemented retrieve->generate graph; the others are
registered but not yet implemented.

Retrieval runs once (pgvector default, or mongodb). The answer is then generated by EVERY
enabled LLM provider (see providers.py) over the same sources, so quality can be compared.
"""
import logging
from typing import Optional

from . import config, providers
from .search import search_chunks

log = logging.getLogger("vehicle-explore")

IMPLEMENTED = {"langgraph"}
KNOWN = {"langgraph", "crewai", "llamaindex", "haystack"}


def _retrieve(query: str, company_id: Optional[str], top_k: int, store: str) -> list[dict]:
    if store == "mongodb":
        from .mongo_search import search_chunks_mongo  # lazy: pg-only runs need no Mongo
        return search_chunks_mongo(query, company_id, top_k)
    return search_chunks(query, company_id, top_k)


def _extractive_answer(results: list[dict]) -> str:
    top = " ".join(results[0]["snippet"].split())
    return f"Based on {len(results)} matching source(s): {top[:300]}"


def synthesize(query: str, results: list[dict], use_llm: bool = True) -> tuple[str, str, list[dict]]:
    """Returns (primary_answer, answerSource, answers).

    answers = per-provider results (each {provider,label,model,answer,ok,error,latencyMs}).
    primary_answer = the first successful provider's answer, else an extractive summary.
    """
    if not results:
        return "No relevant vehicle content was found for this query.", "none", []
    if not (use_llm and config.LLM_ENABLED):
        return _extractive_answer(results), "extractive", []

    answers = providers.generate_all(query, results)
    ok = [a for a in answers if a.get("ok")]
    if ok:
        return ok[0]["answer"], "llm", answers
    log.warning("All %d LLM provider(s) failed; using extractive answer", len(answers))
    return _extractive_answer(results), "extractive", answers


def run(framework: str, query: str, company_id: Optional[str], top_k: int,
        store: str, use_llm: bool = True) -> tuple[str, str, list[dict], list[dict]]:
    if framework == "langgraph":
        from . import langgraph_agent  # real LangGraph StateGraph (lazy import)
        return langgraph_agent.run(query, company_id, top_k, store, use_llm)
    results = _retrieve(query, company_id, top_k, store)
    answer, source, answers = synthesize(query, results, use_llm)
    return answer, source, results, answers
