"""AI framework router. The framework name is part of the URL
(/api/vehicle-explore/{framework}/search) so requests can route to different agent
implementations. 'langgraph' is the implemented retrieve->generate graph; the others are
registered but not yet implemented.

Retrieval runs once (pgvector default, or mongodb). The answer is then generated by EVERY
enabled LLM provider (see providers.py) over the same sources, so quality can be compared.
"""
import logging
import re
from contextvars import ContextVar
from typing import Optional

from . import config, providers, search

log = logging.getLogger("vehicle-explore.frameworks")

IMPLEMENTED = {"langgraph", "crewai", "llamaindex", "haystack", "plan-execute", "auto"}
KNOWN = {"langgraph", "crewai", "llamaindex", "haystack", "plan-execute", "auto"}

# When the 'auto' meta-framework routes a request, the framework it chose (read by main.py for the UI).
ROUTED: ContextVar[str] = ContextVar("routed_framework", default="")

_COMPARE_RE = re.compile(
    r"\b(compare|comparison|versus|vs\.?|difference|differences|which (is|one|of)|"
    r"cheapest|best|better|pros and cons|trade[- ]?offs?)\b", re.I)
_MAKES = {"toyota", "lexus", "honda", "acura", "ford", "lincoln", "chevrolet", "gmc", "buick",
          "cadillac", "jeep", "ram", "dodge", "chrysler", "fiat", "maserati", "volkswagen", "vw",
          "audi", "porsche", "bentley", "lamborghini", "bmw", "mini", "mercedes", "hyundai", "kia",
          "genesis", "nissan", "infiniti", "volvo", "polestar", "jaguar", "mazda", "subaru",
          "mitsubishi", "tesla", "rivian", "ferrari"}


def _is_compound(query: str) -> bool:
    """Cheap heuristic: a query is 'compound' (worth planning) if it compares things, mentions
    multiple brands, or stacks several facets — otherwise a single retrieval (langgraph) is fine."""
    q = (query or "").lower()
    if _COMPARE_RE.search(q):
        return True
    if sum(1 for m in _MAKES if m in q) >= 2:
        return True
    return (q.count(" and ") + q.count(",")) >= 2

# Retrieval mode for the current request (vector | fts | hybrid), set by run() so the four
# agent implementations don't each need a new parameter threaded through their signatures.
_RETRIEVAL_MODE: ContextVar[str] = ContextVar("retrieval_mode", default="vector")


def _retrieve(query: str, company_id: Optional[str], top_k: int, store: str) -> list[dict]:
    if store == "mongodb":
        from .mongo_search import search_chunks_mongo  # lazy: pg-only runs need no Mongo
        return search_chunks_mongo(query, company_id, top_k)
    mode = _RETRIEVAL_MODE.get()
    if mode == "fts":
        return search.search_chunks_fts(query, company_id, top_k)
    if mode == "hybrid":
        return search.search_chunks_hybrid(query, company_id, top_k)
    return search.search_chunks(query, company_id, top_k)


def _extractive_answer(results: list[dict]) -> str:
    top = " ".join(results[0]["snippet"].split())
    return f"Based on {len(results)} matching source(s): {top[:300]}"


def synthesize(query: str, results: list[dict], use_llm: bool = True,
               provider_ids: Optional[list[str]] = None) -> tuple[str, str, list[dict]]:
    """Returns (primary_answer, answerSource, answers).

    answers = per-provider results (each {provider,label,model,answer,ok,error,tokens,cost,latency}).
    primary_answer = the first successful provider's answer, else an extractive summary.
    """
    if not results:
        return "No relevant vehicle content was found for this query.", "none", []
    if not (use_llm and config.LLM_ENABLED):
        return _extractive_answer(results), "extractive", []

    answers = providers.generate_all(query, results, provider_ids)
    if not answers:
        return _extractive_answer(results), "extractive", []
    ok = [a for a in answers if a.get("ok")]
    if ok:
        return ok[0]["answer"], "llm", answers
    log.warning("All %d LLM provider(s) failed; using extractive answer", len(answers))
    return _extractive_answer(results), "extractive", answers


def run(framework: str, query: str, company_id: Optional[str], top_k: int, store: str,
        use_llm: bool = True, provider_ids: Optional[list[str]] = None,
        mode: str = "vector") -> tuple[str, str, list[dict], list[dict]]:
    _RETRIEVAL_MODE.set(mode)   # read by _retrieve, including inside the four agent implementations
    if framework == "auto":
        target = "plan-execute" if _is_compound(query) else "langgraph"
        ROUTED.set(target)
        log.info("auto-router: %r -> %s", (query or "")[:60], target)
        return run(target, query, company_id, top_k, store, use_llm, provider_ids, mode)
    if framework == "langgraph":
        from . import langgraph_agent  # real LangGraph StateGraph (lazy import)
        return langgraph_agent.run(query, company_id, top_k, store, use_llm, provider_ids)
    if framework == "crewai":
        from . import crewai_agent  # real CrewAI 2-agent crew (lazy import — heavy)
        return crewai_agent.run(query, company_id, top_k, store, use_llm, provider_ids)
    if framework == "llamaindex":
        from . import llamaindex_agent  # real LlamaIndex RetrieverQueryEngine (lazy import)
        return llamaindex_agent.run(query, company_id, top_k, store, use_llm, provider_ids)
    if framework == "haystack":
        from . import haystack_agent  # real Haystack 2.x RAG Pipeline (lazy import)
        return haystack_agent.run(query, company_id, top_k, store, use_llm, provider_ids)
    if framework == "plan-execute":
        from . import plan_execute_agent  # Plan-and-Execute: decompose -> retrieve each -> synthesize
        return plan_execute_agent.run(query, company_id, top_k, store, use_llm, provider_ids)
    results = _retrieve(query, company_id, top_k, store)
    answer, source, answers = synthesize(query, results, use_llm, provider_ids)
    return answer, source, results, answers
